# 使用pickle序列化numpy array

In [1]:
import pickle
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
f = open('x.pkl', 'wb')

In [5]:
pickle.dump(x, f)

In [7]:
!dir

 驱动器 C 中的卷是 OS
 卷的序列号是 F8ED-C186

 C:\Users\83707\Py_Data_Analysis 的目录

2020/02/28  14:46    <DIR>          .
2020/02/28  14:46    <DIR>          ..
2020/02/28  14:34    <DIR>          .ipynb_checkpoints
2020/02/28  13:29             8,779 Array.ipynb
2020/02/28  14:46             1,582 Array_input_output.ipynb
2020/02/28  14:25            16,812 Array_matrix_operations.ipynb
2020/02/28  11:50             1,357 helloworld.ipynb
2020/02/28  14:45                 0 x.pkl
               5 个文件         28,530 字节
               3 个目录 617,289,768,960 可用字节


In [8]:
f = open('x.pkl', 'rb')

In [9]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

使用numpy序列化

In [10]:
np.save('one_array', x)

In [11]:
!dir

 驱动器 C 中的卷是 OS
 卷的序列号是 F8ED-C186

 C:\Users\83707\Py_Data_Analysis 的目录

2020/02/28  14:48    <DIR>          .
2020/02/28  14:48    <DIR>          ..
2020/02/28  14:34    <DIR>          .ipynb_checkpoints
2020/02/28  13:29             8,779 Array.ipynb
2020/02/28  14:48             3,059 Array_input_output.ipynb
2020/02/28  14:25            16,812 Array_matrix_operations.ipynb
2020/02/28  11:50             1,357 helloworld.ipynb
2020/02/28  14:48               168 one_array.npy
2020/02/28  14:47               195 x.pkl
               6 个文件         30,370 字节
               3 个目录 617,294,233,600 可用字节


In [12]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
y = np.arange(20)

In [14]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
np.savez('two_array.npz', a=x, b=y)

In [16]:
!dir

 驱动器 C 中的卷是 OS
 卷的序列号是 F8ED-C186

 C:\Users\83707\Py_Data_Analysis 的目录

2020/02/28  14:52    <DIR>          .
2020/02/28  14:52    <DIR>          ..
2020/02/28  14:34    <DIR>          .ipynb_checkpoints
2020/02/28  13:29             8,779 Array.ipynb
2020/02/28  14:52             5,282 Array_input_output.ipynb
2020/02/28  14:25            16,812 Array_matrix_operations.ipynb
2020/02/28  11:50             1,357 helloworld.ipynb
2020/02/28  14:48               168 one_array.npy
2020/02/28  14:52               610 two_array.npz
2020/02/28  14:47               195 x.pkl
               7 个文件         33,203 字节
               3 个目录 617,291,161,600 可用字节


In [17]:
c = np.load('two_array.npz')

In [18]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])