# 快速创建数组

In [3]:
import numpy as np

In [4]:
# 符合正态分布
np.random.randn(10)

array([ 0.47986524,  0.72836279,  1.30247327, -0.6780892 , -0.04029298,
       -0.04132731,  0.2233451 , -1.48201137, -0.4009798 ,  2.25031873])

In [11]:
# 返回10以内的随机数
np.random.randint(10, size=(2,3))

array([[3, 3, 1],
       [6, 3, 9]])

In [13]:
np.random.randint(10, size=20).reshape(4,5)

array([[3, 8, 8, 1, 8],
       [1, 6, 9, 1, 8],
       [6, 2, 6, 4, 9],
       [1, 8, 7, 3, 8]])

# 数组运算

In [14]:
a = np.random.randint(10, size=20).reshape(4,5)

In [15]:
b = np.random.randint(10, size=20).reshape(4,5)

In [16]:
a

array([[8, 0, 6, 1, 7],
       [9, 2, 9, 9, 4],
       [2, 3, 0, 3, 1],
       [5, 2, 1, 7, 3]])

In [17]:
b

array([[3, 8, 5, 5, 6],
       [8, 7, 2, 6, 9],
       [0, 2, 2, 1, 7],
       [2, 7, 8, 7, 5]])

In [18]:
a + b

array([[11,  8, 11,  6, 13],
       [17,  9, 11, 15, 13],
       [ 2,  5,  2,  4,  8],
       [ 7,  9,  9, 14,  8]])

In [19]:
a - b

array([[ 5, -8,  1, -4,  1],
       [ 1, -5,  7,  3, -5],
       [ 2,  1, -2,  2, -6],
       [ 3, -5, -7,  0, -2]])

In [20]:
a * b

array([[24,  0, 30,  5, 42],
       [72, 14, 18, 54, 36],
       [ 0,  6,  0,  3,  7],
       [10, 14,  8, 49, 15]])

In [22]:
# 除数不能为零
a / b

C:\Z_TOOL\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[2.66666667, 0.        , 1.2       , 0.2       , 1.16666667],
       [1.125     , 0.28571429, 4.5       , 1.5       , 0.44444444],
       [       inf, 1.5       , 0.        , 3.        , 0.14285714],
       [2.5       , 0.28571429, 0.125     , 1.        , 0.6       ]])

In [23]:
np.mat([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [24]:
a

array([[8, 0, 6, 1, 7],
       [9, 2, 9, 9, 4],
       [2, 3, 0, 3, 1],
       [5, 2, 1, 7, 3]])

In [25]:
np.mat(a)

matrix([[8, 0, 6, 1, 7],
        [9, 2, 9, 9, 4],
        [2, 3, 0, 3, 1],
        [5, 2, 1, 7, 3]])

# 矩阵的运算

In [26]:
A = np.mat(a)

In [27]:
B = np.mat(b)

In [28]:
A

matrix([[8, 0, 6, 1, 7],
        [9, 2, 9, 9, 4],
        [2, 3, 0, 3, 1],
        [5, 2, 1, 7, 3]])

In [29]:
B

matrix([[3, 8, 5, 5, 6],
        [8, 7, 2, 6, 9],
        [0, 2, 2, 1, 7],
        [2, 7, 8, 7, 5]])

In [30]:
A + B

matrix([[11,  8, 11,  6, 13],
        [17,  9, 11, 15, 13],
        [ 2,  5,  2,  4,  8],
        [ 7,  9,  9, 14,  8]])

In [31]:
A - B

matrix([[ 5, -8,  1, -4,  1],
        [ 1, -5,  7,  3, -5],
        [ 2,  1, -2,  2, -6],
        [ 3, -5, -7,  0, -2]])

In [33]:
# 矩阵乘法必须是mp乘pn
A * B

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [34]:
c = np.mat(np.random.randint(10, size=20).reshape(4,5))

In [35]:
d = np.mat(np.random.randint(10, size=20).reshape(5,4))

In [36]:
c

matrix([[4, 6, 7, 6, 7],
        [2, 4, 7, 0, 7],
        [5, 4, 6, 8, 9],
        [9, 0, 0, 2, 7]])

In [37]:
d

matrix([[1, 2, 8, 0],
        [8, 1, 8, 7],
        [1, 5, 6, 4],
        [3, 6, 1, 1],
        [8, 3, 5, 9]])

In [38]:
c * d

matrix([[133, 106, 163, 139],
        [ 97,  64, 125, 119],
        [139, 119, 161, 141],
        [ 71,  51, 109,  65]])

# Array常用函数

In [39]:
e = np.random.randint(10, size=20).reshape(4,5)

In [40]:
e

array([[1, 6, 9, 2, 5],
       [2, 4, 6, 8, 5],
       [9, 9, 3, 6, 1],
       [9, 2, 5, 0, 4]])

In [41]:
np.unique(e)

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [43]:
# 默认返回各column的和
sum(e)

array([21, 21, 23, 16, 15])

In [46]:
# 求具体某一row的和
sum(e[1])

25

In [48]:
# 返回第一个column的和
sum(e[:,0])

21

In [50]:
# 整个array中的最大值
e.max()

9

In [51]:
# 第0row的最大值
max(e[0])

9

In [52]:
# 第0column的最大值
max(e[:,0])

9