In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# Concatenate

Array - Matrix concatenate

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
arr2 = np.arange(9).reshape(3,3)

In [5]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.concatenate([arr1,arr2], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.concatenate([arr1,arr2], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

Series - pd.concat

In [9]:
s1 = Series([1,2,3], index=['X','Y','Z'])

In [10]:
s2 = Series([4,5],index=['A','B'])

In [11]:
s1

X    1
Y    2
Z    3
dtype: int64

In [12]:
s2

A    4
B    5
dtype: int64

In [13]:
pd.concat([s1,s2])

X    1
Y    2
Z    3
A    4
B    5
dtype: int64

In [14]:
pd.concat([s1,s2], axis=1)

0    1
X  1.0  NaN
Y  2.0  NaN
Z  3.0  NaN
A  NaN  4.0
B  NaN  5.0

Dataframe - pd.concat

In [15]:
df1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

In [16]:
df1

X         Y         Z
0 -0.143198  0.383842  1.522704
1 -0.187855 -0.595196 -0.612653
2 -1.336210  0.030145  0.037641
3  0.489209 -0.132080  1.031712

In [19]:
df2 = DataFrame(np.random.randn(3,3), columns=['X','Y','A'])

In [20]:
df2

X         Y         A
0 -1.041970 -0.705421  0.181825
1  0.956096 -1.519657 -0.132210
2 -0.087008  0.205570  1.318948

In [22]:
pd.concat([df1,df2])

X         Y         Z         A
0 -0.143198  0.383842  1.522704       NaN
1 -0.187855 -0.595196 -0.612653       NaN
2 -1.336210  0.030145  0.037641       NaN
3  0.489209 -0.132080  1.031712       NaN
0 -1.041970 -0.705421       NaN  0.181825
1  0.956096 -1.519657       NaN -0.132210
2 -0.087008  0.205570       NaN  1.318948

# Combine

In [23]:
s1 = Series([2,np.nan,4,np.nan],index=['A','B','C','D'])

In [24]:
s1

A    2.0
B    NaN
C    4.0
D    NaN
dtype: float64

In [25]:
s2 = Series([1,2,3,4],index=['A','B','C','D'])

In [26]:
s2

A    1
B    2
C    3
D    4
dtype: int64

In [28]:
# combine_first 是用s2去填充s1中没有的值
s1.combine_first(s2)

A    2.0
B    2.0
C    4.0
D    4.0
dtype: float64

In [29]:
df1 = DataFrame({'X':[1,np.nan,3,np.nan],'Y':[5,np.nan,7,np.nan],'Z':[9,np.nan,11,np.nan]})

In [30]:
df1

X    Y     Z
0  1.0  5.0   9.0
1  NaN  NaN   NaN
2  3.0  7.0  11.0
3  NaN  NaN   NaN

In [31]:
df2 = DataFrame({'X':[np.nan,10,np.nan,12],'A':[1,2,3,4]})

In [32]:
df2

X  A
0   NaN  1
1  10.0  2
2   NaN  3
3  12.0  4

In [33]:
df1.combine_first(df2)

A     X    Y     Z
0  1.0   1.0  5.0   9.0
1  2.0  10.0  NaN   NaN
2  3.0   3.0  7.0  11.0
3  4.0  12.0  NaN   NaN