In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./data/HR.csv')

In [3]:
df

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14997                0.11             0.96               6   
14998                0.37             0.52               2   
14999                 NaN             0.52               2   
15000                 NaN        999999.00               2   
15001                0.70             0.40               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
0                        157                   3              0     1   
1                        262                   6              0     1   
2                        272                   4              0     1   
3                        223                   5              0     1   
4                        159                   3              0     1   
...                      ...                 ...            ...   ...   
14997                    280                   4              0     1   
14998                    158                   3              0     1   
14999                    158                   3              0     1   
15000                    158                   3              0     1   
15001                    158                   2              0     1   

       promotion_last_5years department  salary  
0                          0      sales     low  
1                          0      sales  medium  
2                          0      sales  medium  
3                          0      sales     low  
4                          0      sales     low  
...                      ...        ...     ...  
14997                      0    support     low  
14998                      0    support     low  
14999                      0    support     low  
15000                      0       sale     low  
15001                      0       sale     nme  

[15002 rows x 10 columns]

In [4]:
amh_s = df['average_monthly_hours']

In [5]:
amh_s.describe()

count    15002.000000
mean       201.041728
std         49.941815
min         96.000000
25%        156.000000
50%        200.000000
75%        245.000000
max        310.000000
Name: average_monthly_hours, dtype: float64

In [6]:
amh_s.median()

200.0

In [7]:
amh_s.skew()

0.05322458779916304

In [8]:
amh_s.kurt()

-1.1350158577565719

剔除异常值

In [9]:
amh_s = amh_s[amh_s<amh_s.quantile(0.75)+1.5*(amh_s.quantile(0.75)-amh_s.quantile(0.25))][amh_s>amh_s.quantile(0.25)-1.5*(amh_s.quantile(0.75)-amh_s.quantile(0.25))]

In [11]:
len(amh_s)

15002

In [13]:
np.histogram(amh_s.values, bins=10)

(array([ 367, 1240, 2736, 1722, 1628, 1712, 1906, 2240, 1127,  324],
       dtype=int64),
 array([ 96. , 117.4, 138.8, 160.2, 181.6, 203. , 224.4, 245.8, 267.2,
        288.6, 310. ]))

In [14]:
# 取值左闭右开
np.histogram(amh_s.values, bins=np.arange(amh_s.min(), amh_s.max()+10, 10))

(array([ 168,  171,  147,  807, 1153, 1234, 1075,  824,  818,  758,  751,
         738,  856,  824,  987, 1002, 1045,  935,  299,  193,  131,   86],
       dtype=int64),
 array([ 96, 106, 116, 126, 136, 146, 156, 166, 176, 186, 196, 206, 216,
        226, 236, 246, 256, 266, 276, 286, 296, 306, 316]))

In [16]:
# 取值左开右闭
amh_s.value_counts(bins=np.arange(amh_s.min(), amh_s.max()+10, 10))

(146.0, 156.0]     1277
(136.0, 146.0]     1159
(256.0, 266.0]     1063
(236.0, 246.0]     1006
(156.0, 166.0]      995
(246.0, 256.0]      987
(126.0, 136.0]      886
(216.0, 226.0]      873
(266.0, 276.0]      860
(166.0, 176.0]      832
(226.0, 236.0]      814
(176.0, 186.0]      813
(186.0, 196.0]      761
(196.0, 206.0]      755
(206.0, 216.0]      731
(276.0, 286.0]      319
(95.999, 106.0]     187
(286.0, 296.0]      164
(116.0, 126.0]      162
(106.0, 116.0]      162
(296.0, 306.0]      128
(306.0, 316.0]       68
Name: average_monthly_hours, dtype: int64