In [1]:
import numpy as np
import pandas as pd

# LDA

In [2]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [3]:
X = np.array([[-1,-1],[-2,-1],[-3,-2],[1,1],[2,1],[3,2]])

In [4]:
Y = np.array([1,1,1,2,2,2])

In [5]:
LinearDiscriminantAnalysis(n_components=1).fit_transform(X,Y)

array([[-1.73205081],
       [-1.73205081],
       [-3.46410162],
       [ 1.73205081],
       [ 1.73205081],
       [ 3.46410162]])

分类判别器

fisher classifier

In [6]:
clf = LinearDiscriminantAnalysis(n_components=1).fit(X,Y)

In [7]:
clf.predict([[0.8,1]])

array([2])

In [8]:
LinearDiscriminantAnalysis(n_components=1).fit_transform(X,Y)[2]

array([-3.46410162])