In [1]:
import numpy as np
import pandas as pd

# 一. 离散化

In [3]:
lst = [6,8,10,15,16,24,25,40,67]

等深分箱 - 相同个数

In [4]:
pd.qcut(lst, q=3)

[(5.999, 13.333], (5.999, 13.333], (5.999, 13.333], (13.333, 24.333], (13.333, 24.333], (13.333, 24.333], (24.333, 67.0], (24.333, 67.0], (24.333, 67.0]]
Categories (3, interval[float64]): [(5.999, 13.333] < (13.333, 24.333] < (24.333, 67.0]]

In [5]:
pd.qcut(lst, q=3, labels=['low','medium','high'])

[low, low, low, medium, medium, medium, high, high, high]
Categories (3, object): [low < medium < high]

等宽分箱 - 相同间距

In [6]:
pd.cut(lst, bins=3)

[(5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (26.333, 46.667], (46.667, 67.0]]
Categories (3, interval[float64]): [(5.939, 26.333] < (26.333, 46.667] < (46.667, 67.0]]

In [7]:
pd.cut(lst, bins=3, labels=['low','medium','high'])

[low, low, low, low, low, low, low, medium, high]
Categories (3, object): [low < medium < high]

# 二. 归一化与标准化

In [9]:
# 引入归一化与标准化函数
from sklearn.preprocessing import MinMaxScaler, StandardScaler

归一化

In [10]:
MinMaxScaler().fit_transform(np.array([1,4,10,15,21]).reshape(-1,1))

array([[0.  ],
       [0.15],
       [0.45],
       [0.7 ],
       [1.  ]])

Z-score标准化

In [11]:
StandardScaler().fit_transform(np.array([1,1,1,1,0,0,0,0]).reshape(-1,1))

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.]])

In [13]:
StandardScaler().fit_transform(np.array([1,0,0,0,0,0,0,0]).reshape(-1,1))

array([[ 2.64575131],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447]])

# 三. 数值化

In [14]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

标签化

In [17]:
LabelEncoder().fit_transform(np.array(['Down','Up','Up','Down']).reshape(-1,1))

array([0, 1, 1, 0], dtype=int64)

In [18]:
LabelEncoder().fit_transform(np.array(['Low','Medium','High','Medium','Low']).reshape(-1,1))

array([1, 2, 0, 2, 1], dtype=int64)

独热

In [19]:
lb_encoder=LabelEncoder()

In [23]:
lb_tran_f = lb_encoder.fit_transform(np.array(['Red','Yellow','Blue','Green','Green']))

In [24]:
oht_encoder=OneHotEncoder()

In [28]:
oht_tran_f=oht_encoder.fit_transform(lb_tran_f.reshape(-1,1))

In [29]:
oht_tran_f

<5x4 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [30]:
oht_tran_f.toarray()

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.]])

# 四. 正规化

In [32]:
from sklearn.preprocessing import Normalizer

In [34]:
Normalizer(norm='l1').fit_transform(np.array([[1,1,3,-1,2]]))

array([[ 0.125,  0.125,  0.375, -0.125,  0.25 ]])

In [35]:
Normalizer(norm='l2').fit_transform(np.array([[1,1,3,-1,2]]))

array([[ 0.25,  0.25,  0.75, -0.25,  0.5 ]])