In [1]:
import numpy as np
import pandas as pd
import scipy.stats as ss

In [3]:
df = pd.DataFrame({'A':ss.norm.rvs(size=10),'B':ss.norm.rvs(size=10),'C':ss.norm.rvs(size=10),'D':np.random.randint(low=0,high=2,size=10)})

In [4]:
df

A         B         C  D
0 -1.414159 -2.342991 -0.280619  0
1 -0.699956 -1.057047  1.934925  1
2 -1.938702  0.506251 -1.226774  1
3 -0.117380  0.469089  0.312033  1
4 -0.817622 -0.975774 -1.098236  0
5 -0.227278 -0.662887 -0.387319  0
6 -0.807011  0.077047 -0.784159  1
7 -0.976588  0.058781  1.216638  1
8  0.659450 -0.025512 -0.444237  0
9 -0.207010  0.674560  1.025777  0

In [5]:
from sklearn.svm import SVR

In [6]:
from sklearn.tree import DecisionTreeRegressor

In [7]:
# 特征
X = df.loc[:,['A','B','C']]

In [8]:
# 标注
Y = df.loc[:,'D']

In [9]:
from sklearn.feature_selection import SelectKBest,RFE,SelectFromModel

# 过滤思想

In [10]:
skb = SelectKBest(k=2)

In [11]:
skb.fit(X,Y)

SelectKBest(k=2, score_func=<function f_classif at 0x0000017C5963F678>)

In [13]:
skb.transform(X)

array([[-1.41415851, -2.34299127],
       [-0.69995556, -1.05704721],
       [-1.93870171,  0.50625098],
       [-0.11737991,  0.46908912],
       [-0.81762226, -0.97577357],
       [-0.22727809, -0.66288679],
       [-0.80701088,  0.07704728],
       [-0.97658826,  0.05878147],
       [ 0.65945017, -0.02551245],
       [-0.20700993,  0.67455979]])

# 包裹思想

In [14]:
rfe = RFE(estimator=SVR(kernel='linear'),n_features_to_select=2,step=1)

In [16]:
rfe.fit_transform(X,Y)

array([[-1.41415851, -2.34299127],
       [-0.69995556, -1.05704721],
       [-1.93870171,  0.50625098],
       [-0.11737991,  0.46908912],
       [-0.81762226, -0.97577357],
       [-0.22727809, -0.66288679],
       [-0.80701088,  0.07704728],
       [-0.97658826,  0.05878147],
       [ 0.65945017, -0.02551245],
       [-0.20700993,  0.67455979]])

# 嵌入思想

In [17]:
sfm = SelectFromModel(estimator=DecisionTreeRegressor(),threshold=0.1)

In [18]:
sfm.fit_transform(X,Y)

array([[-2.34299127, -0.28061933],
       [-1.05704721,  1.93492532],
       [ 0.50625098, -1.22677369],
       [ 0.46908912,  0.31203257],
       [-0.97577357, -1.09823629],
       [-0.66288679, -0.38731926],
       [ 0.07704728, -0.78415903],
       [ 0.05878147,  1.21663817],
       [-0.02551245, -0.44423674],
       [ 0.67455979,  1.02577666]])